<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<title>Administration</title>

	<link type="text/css" href="css/screen.css" rel="stylesheet" media="all" />
</head>
<body>
<div class="header">
	<ul>
		<li class="current"><a href="<?php echo $_SERVER["SCRIPT_NAME"] ?>?action=changePassword">Change Password</a></li>
		<?php if($firewall->hasUserAccess()) : ?>
		<li><a href="<?php echo $_SERVER["SCRIPT_NAME"] ?>?action=listUsers">List Users</a></li>
		<?php endif; ?>
	</ul>
</div>

<h1>Change your password</h1>

<?php if (isset($_GET['success'])) : ?>
<div class="flash">
	<?php if (empty($_GET['message'])) : ?>
	<div class="success">Password changed successfully.</div>
	<?php else : ?>
	<div class="error"><?php echo $_GET['message'] ?></div>
	<?php endif; ?>
</div>
<?php endif; ?>

<div id="main_content">
	<form action="<?php echo $_SERVER["SCRIPT_NAME"] ?>?action=updatePassword" method="post">
		<fieldset>
			<label for="user_password">Enter new password:</label>
			<br>
			<input type="password" name="password" id="user_password" />
			<br>
			<label for="user_password_retype">Retype new password:</label>
			<br>
			<input type="password" name="pwretype" id="user_password_retype" />
		</fieldset>

		<input type="submit" value="Submit" />
	</form>
</div>
</body>
</html>