<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<title>Administration</title>

	<link type="text/css" href="css/screen.css" rel="stylesheet" media="all" />
</head>
<body>
<div class="header">
	<ul>
		<li><a href="/?action=changePassword">Mein Passwort ändern</a></li>
		<?php if($firewall->hasUserAccess()) : ?>
		<li><a href="/?action=listUsers">Benutzer auflisten</a></li>
		<?php endif; ?>
	</ul>
</div>

<h1>Error 403</h1>

<?php if (isset($_GET['success'])) : ?>
<div class="flash">
	<?php if (empty($_GET['message'])) : ?>
	<div class="success">Passwort wurde erfolgreich geändert.</div>
	<?php else : ?>
	<div class="error"><?php echo $_GET['message'] ?></div>
	<?php endif; ?>
</div>
<?php endif; ?>

<div id="main_content">
	<h2 style="text-align: center; margin-top: 7em;">403</h2>
	<h3 style="text-align: center; margin-top: 1em;">Zugriff verweigert</h3>
</div>
</body>
</html>